<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVrbjkqp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVrbjkqp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVrbjkqp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVrbjkqp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVrbjkqp\appProdProjectContainer([
    'container.build_hash' => 'Vrbjkqp',
    'container.build_id' => '32c4628d',
    'container.build_time' => 1715981150,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVrbjkqp');
